title: "Diego Palacios Farias"
description: "Assistant Professor | Social Network Analysis | Adolescence | Peer relations | Substance use"
url: "https://diegopalaciosf.github.io"
baseurl: ""

remote_theme: "academicpages/academicpages.github.io@master"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

locale: "en-US"
markdown: kramdown

author: diego
  name: "Diego Palacios Farias"

defaults:
  - scope:
      path: ""
    values:
      author: diego
      author_profile: true

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
