title: "Diego Palacios Farias"
description: "Assistant Professor | Social Network Analysis | Adolescence | Peer relations | Substance use"
url: "https://diegopalaciosf.github.io"
baseurl: ""

remote_theme: "academicpages/academicpages.github.io@master"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

locale: "en-US"
markdown: kramdown

author:
  name: "Diego Palacios Farias"
  avatar: "/images/profile.png" 
  avatar_url: "/images/profile.png"
# IMPORTANT: publish pages stored in _pages
include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      author: diego
      author_profile: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
